import type { PostType } from "../types/PostTypes"

export const dummyPost: PostType[] = [
  {
    name: "Alex Rivera",
    time: "Just now",
    description: "Finally finished my portfolio site! 🚀 Check it out and let me know your thoughts.",
    location: "San Diego, CA",
    like_count: 45,
    comment_count: 7,
    repost_count: 2,
    share_count: 3,
  },
  {
    name: "Maya Chen",
    time: "30 minutes ago",
    description: "Sunsets by the beach just hit different. 🌅",
    location: "Santa Monica, CA",
    like_count: 102,
    comment_count: 9,
    repost_count: 3,
    share_count: 6,
  },
  {
    name: "Ethan Brooks",
    time: "1 hour ago",
    description: "Ran my first 10K today. Feeling sore but accomplished! 💪",
    location: "Austin, TX",
    like_count: 88,
    comment_count: 5,
    repost_count: 1,
    share_count: 2,
  },
  {
    name: "Layla Hassan",
    time: "2 hours ago",
    description: "This new cafe downtown has the best matcha I've ever had 🍵",
    location: "Chicago, IL",
    like_count: 134,
    comment_count: 12,
    repost_count: 4,
    share_count: 8,
  },
  {
    name: "Noah Kim",
    time: "5 hours ago",
    description: "Studio day. Nothing better than getting lost in your own music. 🎧🎶",
    location: "Seattle, WA",
    like_count: 93,
    comment_count: 6,
    repost_count: 3,
    share_count: 4,
  },
]
